export enum Emoji {
  greeting = '👋',
  question = '⁉️',
  answer = '👍',
  pushGo = '👇',
  forward = '✅',
  go = '▶️',
  change = '🚫',
  reject = '❌',
  attention = '☝️',
  alert = '❗️',
  pin = '📌',
  time = '⏳',
  book = '📔',
  note = '📝',
  send = '📤',
  restart = '🔄',
  sad = '😔',
  wink = '😉',
}
